otree/urls.py
from otree.extensions import get_extensions_modules, get_extensions_data_export_views
import inspect
from importlib import import_module
from django.templatetags.static import static
from django.conf import urls

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView
from django.conf import settings

from django.contrib.auth.decorators import login_required
from otree import common_internal
from django.http import HttpResponse

STUDY_UNRESTRICTED_VIEWS = {
    'AssignVisitorToRoom',
    'InitializeParticipant',
    'MTurkLandingPage',
    'MTurkStart',
    'JoinSessionAnonymously',
    'OutOfRangeNotification',
    'ParticipantRoomHeartbeat',
}


DEMO_UNRESTRICTED_VIEWS = STUDY_UNRESTRICTED_VIEWS.union({
    'AdminReport',
    'AdvanceSession',
    'CreateDemoSession',
    'DemoIndex',
    'SessionSplitScreen',
    'SessionDescription',
    'SessionMonitor',
    'SessionPayments',
    'SessionData',
    'SessionStartLinks',
    'WaitUntilSessionCreated',
})


def view_classes_from_module(module_name):
    views_module = import_module(module_name)

    # what about custom views?
    return [
        ViewCls for _, ViewCls in inspect.getmembers(views_module)
        if hasattr(ViewCls, 'url_pattern') and
        inspect.getmodule(ViewCls) == views_module
    ]


def url_patterns_from_game_module(module_name, name_in_url):
    views_module = import_module(module_name)

    all_views = [
        ViewCls
        for _, ViewCls in inspect.getmembers(views_module)
        if hasattr(ViewCls, 'url_pattern')]

    view_urls = []
    for ViewCls in all_views:

        url_pattern = ViewCls.url_pattern(name_in_url)
        url_name = ViewCls.url_name()
        view_urls.append(
            urls.url(url_pattern, ViewCls.as_view(), name=url_name)
        )

    return view_urls


def url_patterns_from_module(module_name):
    """automatically generates URLs for all Views in the module,
    So that you don't need to enumerate them all in urlpatterns.
    URLs take the form "gamename/ViewName".
    See the method url_pattern() for more info

    So call this function in your urls.py and pass it the names of all
    Views modules as strings.

    """

    all_views = view_classes_from_module(module_name)

    view_urls = []
    for ViewCls in all_views:
        # automatically assign URL name for reverse(), it defaults to the
        # class's name
        url_name = getattr(ViewCls, 'url_name', ViewCls.__name__)

        if settings.AUTH_LEVEL == 'STUDY':
            unrestricted = url_name in STUDY_UNRESTRICTED_VIEWS
        elif settings.AUTH_LEVEL == 'DEMO':
            unrestricted = url_name in DEMO_UNRESTRICTED_VIEWS
        else:
            unrestricted = True

        if unrestricted:
            as_view = ViewCls.as_view()
        else:
            as_view = login_required(ViewCls.as_view())

        url_pattern = ViewCls.url_pattern
        if callable(url_pattern):
            url_pattern = url_pattern()

        view_urls.append(
            urls.url(url_pattern, as_view, name=url_name)
        )

    return view_urls


def extensions_urlpatterns():

    urlpatterns = []

    for url_module in get_extensions_modules('urls'):
        urlpatterns += getattr(url_module, 'urlpatterns', [])

    return urlpatterns


def extensions_export_urlpatterns():
    view_classes = get_extensions_data_export_views()
    view_urls = []

    for ViewCls in view_classes:
        if settings.AUTH_LEVEL in {'DEMO', 'STUDY'}:
            as_view = login_required(ViewCls.as_view())
        else:
            as_view = ViewCls.as_view()
        view_urls.append(urls.url(ViewCls.url_pattern, as_view, name=ViewCls.url_name))

    return view_urls


def get_urlpatterns():

    from django.contrib.auth.views import login, logout

    urlpatterns = [
        urls.url(r'^$', RedirectView.as_view(url='/demo', permanent=True)),
        urls.url(
            r'^accounts/login/$',
            login,
            {'template_name': 'otree/login.html'},
            name='login_url',
        ),
        urls.url(
            r'^accounts/logout/$',
            logout,
            {'next_page': 'DemoIndex'},
            name='logout',
        ),
    ]

    urlpatterns += staticfiles_urlpatterns()

    used_names_in_url = set()
    for app_name in settings.INSTALLED_OTREE_APPS:
        models_module = common_internal.get_models_module(app_name)
        name_in_url = models_module.Constants.name_in_url
        if name_in_url in used_names_in_url:
            msg = (
                "App {} has Constants.name_in_url='{}', "
                "which is already used by another app"
            ).format(app_name, name_in_url)
            raise ValueError(msg)

        used_names_in_url.add(name_in_url)

        views_module = common_internal.get_pages_module(app_name)
        urlpatterns += url_patterns_from_game_module(
            views_module.__name__, name_in_url)


    urlpatterns += url_patterns_from_module('otree.views.participant')
    urlpatterns += url_patterns_from_module('otree.views.demo')
    urlpatterns += url_patterns_from_module('otree.views.admin')
    urlpatterns += url_patterns_from_module('otree.views.room')
    urlpatterns += url_patterns_from_module('otree.views.mturk')
    urlpatterns += url_patterns_from_module('otree.views.export')

    urlpatterns += extensions_urlpatterns()
    urlpatterns += extensions_export_urlpatterns()

    # serve an empty favicon?
    # otherwise, the logs will contain:
    # [WARNING] django.request > Not Found: /favicon.ico
    # Not Found: /favicon.ico
    # don't want to add a <link> in base template because even if it exists,
    # browsers will still request /favicon.ico.
    # plus it makes the HTML noisier
    # can't use the static() function here because maybe collectstatic
    # has not been run yet
    # and it seems an empty HttpResponse or even a 204 response makes the browser
    # just keep requesting the file with every page load
    # hmmm...now it seems that chrome is not re-requesting with every page load
    # but firefox does. but if i remove the favicon, there's 1 404 then FF doesn't
    # ask for it again.


    # import os
    # dir_path = os.path.dirname(os.path.realpath(__file__))
    # with open(os.path.join(dir_path, 'favicon_invisible.ico'), 'rb') as f:
    # #with open('favicon.ico', 'rb') as f:
    #     favicon_content = f.read()
    #
    #
    # urlpatterns.append(
    #     urls.url(
    #         r'^favicon\.ico$',
    #         lambda request: HttpResponse(favicon_content, content_type="image/x-icon")
    #     )
    # )

    return urlpatterns


urlpatterns = get_urlpatterns()

otree/models/group.py
from otree.db import models
from otree.common_internal import (
    get_models_module, in_round, in_rounds, InvalidRoundError,

)
from otree.models.fieldchecks import ensure_field
import django.core.exceptions
from django.db import models as djmodels


class BaseGroup(models.Model):
    """Base class for all Groups.
    """

    class Meta:
        abstract = True
        index_together = ['session', 'id_in_subsession']
        ordering = ['pk']

    id_in_subsession = models.PositiveIntegerField(db_index=True)

    session = models.ForeignKey(
        'otree.Session', related_name='%(app_label)s_%(class)s',
        on_delete=models.CASCADE
    )

    round_number = models.PositiveIntegerField(db_index=True)

    def __unicode__(self):
        return str(self.pk)

    def get_players(self):
        return list(self.player_set.order_by('id_in_group'))

    def get_player_by_id(self, id_in_group):
        try:
            return self.player_set.get(id_in_group=id_in_group)
        except django.core.exceptions.ObjectDoesNotExist:
            raise ValueError(
                'No player with id_in_group {}'.format(id_in_group)) from None

    def get_player_by_role(self, role):
        for p in self.get_players():
            if p.role() == role:
                return p
        raise ValueError('No player with role {}'.format(role))

    def set_players(self, players_list):
        for i, player in enumerate(players_list, start=1):
            player.group = self
            player.id_in_group = i
            player.save()

    def in_round(self, round_number):
        try:
            return in_round(type(self), round_number, session=self.session,
                id_in_subsession=self.id_in_subsession)
        except InvalidRoundError as exc:
            msg = str(exc) + '; ' + (
                'Hint: you should not use this '
                'method if you are rearranging groups between rounds.'
            )
            ExceptionClass = type(exc)
            raise ExceptionClass(msg) from None

    def in_rounds(self, first, last):
        try:
            return in_rounds(type(self), first, last, session=self.session,
                id_in_subsession=self.id_in_subsession)
        except InvalidRoundError as exc:
            msg = str(exc) + '; ' + (
                'Hint: you should not use this '
                'method if you are rearranging groups between rounds.'
            )
            ExceptionClass = type(exc)
            raise ExceptionClass(msg) from None

    def in_previous_rounds(self):
        return self.in_rounds(1, self.round_number-1)

    def in_all_rounds(self):
        return self.in_previous_rounds() + [self]

    @classmethod
    def _ensure_required_fields(cls):
        """
        Every ``Group`` model requires a foreign key to the ``Subsession``
        model of the same app.
        """
        subsession_model = '{app_label}.Subsession'.format(
            app_label=cls._meta.app_label)
        subsession_field = djmodels.ForeignKey(
            subsession_model, on_delete=models.CASCADE
        )
        ensure_field(cls, 'subsession', subsession_field)

otree/views/export.py
import csv
import datetime

from django.http import HttpResponse
from django.conf import settings

import vanilla

import otree.common_internal
import otree.models
import otree.export
from otree.models.participant import Participant
from otree.models.session import Session
from otree.extensions import get_extensions_data_export_views
from otree.models_concrete import ChatMessage


class ExportIndex(vanilla.TemplateView):

    template_name = 'otree/admin/Export.html'

    url_pattern = r"^export/$"

    def get_context_data(self, **kwargs):
        context = super(ExportIndex, self).get_context_data(**kwargs)

        context['db_is_empty'] = not Participant.objects.exists()

        # can't use settings.INSTALLED_OTREE_APPS, because maybe the app
        # was removed from SESSION_CONFIGS.
        app_names_with_data = set()
        for session in Session.objects.all():
            for app_name in session.config['app_sequence']:
                app_names_with_data.add(app_name)
        context['app_names'] = app_names_with_data
        context['chat_messages_exist'] = ChatMessage.objects.exists()
        context['extensions_views'] = get_extensions_data_export_views()

        return context


class ExportAppDocs(vanilla.View):

    url_pattern = r"^ExportAppDocs/(?P<app_name>[\w.]+)/$"

    def _doc_file_name(self, app_name):
        return '{} - documentation ({}).txt'.format(
            app_name,
            datetime.date.today().isoformat()
        )

    def get(self, request, *args, **kwargs):
        app_name = kwargs['app_name']
        response = HttpResponse(content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(
            self._doc_file_name(app_name)
        )
        otree.export.export_docs(response, app_name)
        return response


def get_export_response(request, file_prefix):
    if bool(request.GET.get('xlsx')):
        content_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        file_extension = 'xlsx'
    else:
        content_type = 'text/csv'
        file_extension = 'csv'
    response = HttpResponse(
        content_type=content_type)
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(
        '{} (accessed {}).{}'.format(
            file_prefix,
            datetime.date.today().isoformat(),
            file_extension
        ))
    return response, file_extension


class ExportApp(vanilla.View):

    url_pattern = r"^ExportApp/(?P<app_name>[\w.]+)/$"

    def get(self, request, *args, **kwargs):

        app_name = kwargs['app_name']
        response, file_extension = get_export_response(request, app_name)
        otree.export.export_app(app_name, response, file_extension=file_extension)
        return response


class ExportWide(vanilla.View):

    url_pattern = r"^ExportWide/$"

    def get(self, request, *args, **kwargs):
        response, file_extension = get_export_response(
            request, 'All apps - wide')
        otree.export.export_wide(response, file_extension)
        return response


class ExportTimeSpent(vanilla.View):

    url_pattern = r"^ExportTimeSpent/$"

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(
            'TimeSpent (accessed {}).csv'.format(
                datetime.date.today().isoformat()
            )
        )
        otree.export.export_time_spent(response)
        return response


class ExportChat(vanilla.View):

    url_pattern = '^otreechatcore_export/$'

    def get(request, *args, **kwargs):

        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="{}"'.format(
            'Chat messages (accessed {}).csv'.format(
                datetime.date.today().isoformat()
            )
        )

        column_names = [
            'participant__session__code',
            'participant__session_id',
            'participant__id_in_session',
            'participant__code',
            'channel',
            'nickname',
            'body',
            'timestamp',
        ]

        rows = ChatMessage.objects.order_by('timestamp').values_list(*column_names)

        writer = csv.writer(response)
        writer.writerows([column_names])
        writer.writerows(rows)

        return response

otree/templates/otree/admin/AdminReport.html
{% extends "otree/admin/Session.html" %}
{% load otree i18n %}


{% block content %}
    {{ block.super }}
    <form action="" method="get" role="form" class="form" id="form">
        <table cellpadding="10">
            <tr>
                <td>{% formfield form.app_name %}</td>
                <td>{% formfield form.round_number %}</td>
                <td>
                    <button type="submit" id="submit" class="btn btn-primary">
                        Go
                    </button>
                </td>
            </tr>
        </table>
    </form>

    {% include user_template %}

    {% if view.is_debug|default:False %}
        <br><br>
        {% include 'otree/includes/debug_info.html' %}
    {% endif %}

    <script>
    $(function() {
        $('#id_app_name').change(function() {
            $('#id_round_number').val('');
        });
    });
    </script>

{% endblock %}

otree/templates/otree/admin/BenPage.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
<!-- Add the title of your page here -->
BENS PAGE
{% endblock %}

{% block content %}
<!-- Add the content of your page here -->
{% endblock %}

otree/templates/otree/admin/DeleteUser.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
    Are you sure you want to delete user {{username}}?
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}


  <button type="submit" class="btn btn-danger">Yes, I'm sure.</button>
</form>
{% endblock %}

otree/templates/otree/admin/EditUser.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
    Account information for {{request.user}}.
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <input type=submit value="submit" />
</form>
{% endblock %}

otree/templates/otree/admin/MTurkCreateHIT.html
{% extends "otree/admin/Session.html" %}
{% load otree i18n %}

{% block content %}

{{ block.super }}

{% if not mturk_ready %}
    <p>MTurk is currently disabled.
        If you want to publish your HIT on MTurk please do the following
        steps:
    </p>

    <table class="table">
        <tr>
            <th>Step</th>
            <th>Done?</th>
        </tr>
        <tr>
            <td>
                Run <code>pip3 install otree[mturk]</code>
                and in your <code>requirements_base.txt</code>,
                replace <code>otree==N.N.N</code> with <code>otree[mturk]==N.N.N</code>.
                This will install oTree along with extra MTurk-specific packages.
            </td>
            <td>{% if boto3_installed %}Yes{% else %}No{% endif %}</td>
        </tr>

        <tr>
            <td>Set the settings <code>AWS_ACCESS_KEY_ID</code> and
            <code>AWS_SECRET_ACCESS_KEY</code></td>
            <td>{% if aws_keys_exist %}Yes{% else %}No{% endif %}</td>
        </tr>
        <tr>
            <td>
                View this page with HTTPS.
                <ol>
                    <li>
                    If using Heroku, you can simply change the URL
                    in your browser's address bar to start with 'https://'
                    and reload this page.
                    </li>
                    <!-- disabled until we upgrade channels
                    <li>
                        If running locally, first
                        restart the server with <code>otree runprodserver
                        --dev-https</code>,
                        then change the URL
                        in your browser's address bar to start with 'https://'
                        and reload this page. (You may get a security warning at first)
                    </li>
                    -->
                </ol>
            </td>
            <td>{% if https %}Yes{% else %}No{% endif %}</td>
        </tr>
    </table>

    <p>
        You can read more about Amazon Mechanical Turk integration
        <a href="http://otree.readthedocs.org/en/latest/mturk.html"
           target="_blank">here</a>.
    </p>
{% else %}
    {% if form.errors %}
        <div class="alert alert-danger">
        {% blocktrans trimmed %}Please fix the errors in the form.{% endblocktrans %}
        </div>
    {% endif %}

    <form action="" method="post" role="form" class="form"
          id="form">{% csrf_token %}

    <div class="modal fade" id="mturk-confirm-publish" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Publish HIT?</h4>
                </div>
                <div class="modal-body">
                    <p>
                        You are about to publish HIT for your session on
                        MTurk. Are you sure?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary"
                            data-dismiss="modal">Cancel
                    </button>
                    <button type="submit" class="btn btn-primary">Publish
                        HIT
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% if not session.mturk_HITId %}
        {% include 'otree/forms/layouts/bootstrap.html' %}
        {% if missing_next_button_warning %}
        <div class="alert alert-warning">
            {{ missing_next_button_warning }}
        </div>
        {% endif %}
        <button type="button"
                data-toggle="modal"
                data-target="#mturk-confirm-publish"
                class="btn btn-primary">
            Publish HIT
        </button>

    {% else %}
        <p>
            You have published HIT for this session on MTurk
            {% if session.mturk_use_sandbox %}
                Sandbox
            {% endif %}
            .</p>
        <p>
            To look at the HIT as <em>requester</em>
            follow this <a href="{{ session.mturk_requester_url }}"
                           target="_blank">link</a>.<br>
            To look at the HIT as a <em>worker</em>
            follow this <a href="{{ session.mturk_worker_url }}"
                           target="_blank">link</a>.
        </p>
    {% endif %}
    </form>
{% endif %}

{% include "otree/includes/messages.html" %}
{% endblock %}

otree/templates/otree/admin/NewUser.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
    Your account information
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <input type=submit value="submit" />
</form>
{% endblock %}

otree/templates/otree/admin/Password_Change.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
    Reset your password
{% endblock %}

{% block content %}
{% if messages %}
   <h3>Change password</h3>
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success" role="alert">{{ message|escape|safe }}</div>
        {% else %}
            <div class="alert alert-danger" role="alert">{{ message|escape|safe }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

    <form method="post">
      {% csrf_token %}
      {{ form }}
      {{ form.non_field_errors }}
      <br><button class="btn btn-primary" type="submit">Change password</button>
    </form>


{% endblock %}

otree/templates/otree/admin/RoomWithSession.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
    Room: {{ room.display_name }}
{% endblock %}

{% block content %}

    <div class="alert alert-success">
        <a href="{{ session_url }}">Go to active session.</a>
    </div>

    <form method="post" action="{% url "CloseRoom" room.name %}">
        {% csrf_token %}

        <button class="btn btn-primary" id="close-room">
            Close this room
        </button>

    </form>

    {% include "otree/includes/RoomParticipantLinks.html" %}

{% endblock %}

otree/templates/otree/admin/Rooms.html
{% extends "otree/BaseAdmin.html" %}

{% block title %}
    Rooms
{% endblock %}

{% block content %}

<h4>Current rooms:</h4>

{% for room in rooms %}
        <h4>
            <a href="{% url "RoomWithoutSession" room.name %}">{{ room.display_name }}</a>
        </h4>
{% endfor %}

<hr/>

{% endblock %}

otree/templates/otree/admin/Session.html
{% extends "otree/BaseAdmin.html" %}
{% load otree_internal staticfiles %}

{% block head_title %}
{{ session.config.display_name }}: session '{{ session.code }}'{% if session.is_demo %} (demo) {% endif %}
{% endblock %}

{% block title %}
{{ session.config.display_name }}: session <code>{{ session.code }}</code>{% if session.is_demo %} (demo) {% endif %}
{% endblock %}

{% block menus %}
<ul class="nav nav-tabs justify-content-center">
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'SessionDescription' session.code %}" href="{% url 'SessionDescription' session.code %}"><img src='{% static "glyphicons/pushpin.png" %}'> Description</a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'SessionStartLinks' session.code %}" href="{% url 'SessionStartLinks' session.code %}"><img src='{% static "glyphicons/link.png" %}'> Links</a>
    </li>
    {% if not session.is_demo %}
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'SessionEditProperties' session.code %}" href="{% url 'SessionEditProperties' session.code %}"><img src='{% static "glyphicons/pencil.png" %}'> Edit</a>
    </li>
    {% endif %}
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'SessionMonitor' session.code %}" href="{% url 'SessionMonitor' session.code %}"><img src='{% static "glyphicons/eye-open.png" %}'> Monitor</a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'SessionData' session.code %}" href="{% url 'SessionData' session.code %}"><img src='{% static "glyphicons/list-alt.png" %}'> Data</a>
    </li>
    {% if session.is_for_mturk %}
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'MTurkSessionPayments' session.code %}" href="{% url 'MTurkSessionPayments' session.code %}">
    {% else %}
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'SessionPayments' session.code %}" href="{% url 'SessionPayments' session.code %}">
    {% endif %}
            <img src='{% static "glyphicons/usd.png" %}'> Payments
        </a>
    </li>
    {% if session.has_admin_report %}
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'AdminReport' session.code %}" href="{% url 'AdminReport' session.code %}"><img src='{% static "glyphicons/stats.png" %}'> Report</a>
    {% endif %}
    {% if session.is_for_mturk %}
    <li role="presentation" class="nav-item">
        <a class="nav-link {% active_page request 'MTurkCreateHIT' session.code %}" href="{% url 'MTurkCreateHIT' session.code %}"><img src='{% static "glyphicons/cloud.png" %}'> MTurk</a>
    </li>
    {% endif %}
    {% if session.is_demo %}
    <li role="presentation">
        <a class="nav-link" href="{% url 'CreateDemoSession' session.config.name %}" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Recreate session from scratch. You can also copy this link and share with others.">
            <img src='{% static "glyphicons/refresh.png" %}'> New
        </a>
    </li>
    {% endif %}

</ul>
{% endblock %}

otree/templates/otree/admin/SessionPayments.html
{% extends "otree/admin/Session.html" %}
{% block content %}
{{ block.super }}
<div class="container" style='max-width:970px'>
    <p>
    Generated: <strong>{% now "DATETIME_FORMAT" %}</strong>
    </p>


    <h3>Session</h3>
    <table class="table">
        <tr>
            <th>Session config</th>
            <td>{{ session.config.name }}</td>
        </tr>

        <tr>
            <th>Session code</th>
            <td style="font-family: 'Courier New'">{{ session.code }}</td>
        </tr>

        <tr>
            <th>Experimenter name</th>
            <td>{{ session.experimenter_name|default_if_none:"" }}</td>
        </tr>

    </table>

    <h3>Participants</h3>


    <table class="table table-striped">
        <tr>
            <th>Participant code</th>
            <th>Participant label</th>
            <th>Progress</th>
            <th>Participation fee</th>
            <th>Payoff (bonus)</th>
            <th>Total</th>
            <th>Note</th>
        </tr>

        {% for p in participants %}
        <tr>
            <td style="font-family: 'Courier New'">{{ p.code }}</td>
            <td>{{ p.label|default_if_none:"" }}</td>
            <td>{{ p.current_page_ }}</td>
            <td>{{ participation_fee }}</td>
            <td>{{ p.payoff_in_real_world_currency }}</td>
            <td>{{ p.payoff_plus_participation_fee }}</td>
            <td></td>
        </tr>
        {% endfor %}

    </table>

    <h3>Summary</h3>
    <table class="table">
        <tr>
            <th>Total payments</th>
            <td>{{ total_payments }}</td>
        </tr>
        <tr>
            <th>Mean payment</th>
            <td>{{ mean_payment }}</td>
        </tr>
    </table>


    <h3>Notes/Signature</h3>
    <div class="card bg-light">
        <br/>
        <br/>
        <br/>
    </div>
</div>
{% endblock %}