otree/urls.py
from otree.extensions import get_extensions_modules, get_extensions_data_export_views
import inspect
from importlib import import_module
from django.templatetags.static import static
from django.conf import urls

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView
from django.conf import settings

from django.contrib.auth.decorators import login_required
from otree import common_internal
from django.http import HttpResponse

STUDY_UNRESTRICTED_VIEWS = {
    'AssignVisitorToRoom',
    'InitializeParticipant',
    'MTurkLandingPage',
    'MTurkStart',
    'JoinSessionAnonymously',
    'OutOfRangeNotification',
    'ParticipantRoomHeartbeat',
}


DEMO_UNRESTRICTED_VIEWS = STUDY_UNRESTRICTED_VIEWS.union({
    'AdminReport',
    'AdvanceSession',
    'CreateDemoSession',
    'DemoIndex',
    'SessionSplitScreen',
    'SessionDescription',
    'SessionMonitor',
    'SessionPayments',
    'SessionData',
    'SessionStartLinks',
    'WaitUntilSessionCreated',
})


def view_classes_from_module(module_name):
    views_module = import_module(module_name)

    # what about custom views?
    return [
        ViewCls for _, ViewCls in inspect.getmembers(views_module)
        if hasattr(ViewCls, 'url_pattern') and
        inspect.getmodule(ViewCls) == views_module
    ]


def url_patterns_from_game_module(module_name, name_in_url):
    views_module = import_module(module_name)

    all_views = [
        ViewCls
        for _, ViewCls in inspect.getmembers(views_module)
        if hasattr(ViewCls, 'url_pattern')]

    view_urls = []
    for ViewCls in all_views:

        url_pattern = ViewCls.url_pattern(name_in_url)
        url_name = ViewCls.url_name()
        view_urls.append(
            urls.url(url_pattern, ViewCls.as_view(), name=url_name)
        )

    return view_urls


def url_patterns_from_module(module_name):
    """automatically generates URLs for all Views in the module,
    So that you don't need to enumerate them all in urlpatterns.
    URLs take the form "gamename/ViewName".
    See the method url_pattern() for more info

    So call this function in your urls.py and pass it the names of all
    Views modules as strings.

    """

    all_views = view_classes_from_module(module_name)

    view_urls = []
    for ViewCls in all_views:
        # automatically assign URL name for reverse(), it defaults to the
        # class's name
        url_name = getattr(ViewCls, 'url_name', ViewCls.__name__)

        if settings.AUTH_LEVEL == 'STUDY':
            unrestricted = url_name in STUDY_UNRESTRICTED_VIEWS
        elif settings.AUTH_LEVEL == 'DEMO':
            unrestricted = url_name in DEMO_UNRESTRICTED_VIEWS
        else:
            unrestricted = True

        if unrestricted:
            as_view = ViewCls.as_view()
        else:
            as_view = login_required(ViewCls.as_view())

        url_pattern = ViewCls.url_pattern
        if callable(url_pattern):
            url_pattern = url_pattern()

        view_urls.append(
            urls.url(url_pattern, as_view, name=url_name)
        )

    return view_urls


def extensions_urlpatterns():

    urlpatterns = []

    for url_module in get_extensions_modules('urls'):
        urlpatterns += getattr(url_module, 'urlpatterns', [])

    return urlpatterns


def extensions_export_urlpatterns():
    view_classes = get_extensions_data_export_views()
    view_urls = []

    for ViewCls in view_classes:
        if settings.AUTH_LEVEL in {'DEMO', 'STUDY'}:
            as_view = login_required(ViewCls.as_view())
        else:
            as_view = ViewCls.as_view()
        view_urls.append(urls.url(ViewCls.url_pattern, as_view, name=ViewCls.url_name))

    return view_urls


def get_urlpatterns():

    from django.contrib.auth.views import login, logout

    urlpatterns = [
        urls.url(r'^$', RedirectView.as_view(url='/demo', permanent=True)),
        urls.url(
            r'^accounts/login/$',
            login,
            {'template_name': 'otree/login.html'},
            name='login_url',
        ),
        urls.url(
            r'^accounts/logout/$',
            logout,
            {'next_page': 'DemoIndex'},
            name='logout',
        ),
    ]

    urlpatterns += staticfiles_urlpatterns()

    used_names_in_url = set()
    for app_name in settings.INSTALLED_OTREE_APPS:
        models_module = common_internal.get_models_module(app_name)
        name_in_url = models_module.Constants.name_in_url
        if name_in_url in used_names_in_url:
            msg = (
                "App {} has Constants.name_in_url='{}', "
                "which is already used by another app"
            ).format(app_name, name_in_url)
            raise ValueError(msg)

        used_names_in_url.add(name_in_url)

        views_module = common_internal.get_pages_module(app_name)
        urlpatterns += url_patterns_from_game_module(
            views_module.__name__, name_in_url)


    urlpatterns += url_patterns_from_module('otree.views.participant')
    urlpatterns += url_patterns_from_module('otree.views.demo')
    urlpatterns += url_patterns_from_module('otree.views.admin')
    urlpatterns += url_patterns_from_module('otree.views.room')
    urlpatterns += url_patterns_from_module('otree.views.mturk')
    urlpatterns += url_patterns_from_module('otree.views.export')

    urlpatterns += extensions_urlpatterns()
    urlpatterns += extensions_export_urlpatterns()

    # serve an empty favicon?
    # otherwise, the logs will contain:
    # [WARNING] django.request > Not Found: /favicon.ico
    # Not Found: /favicon.ico
    # don't want to add a <link> in base template because even if it exists,
    # browsers will still request /favicon.ico.
    # plus it makes the HTML noisier
    # can't use the static() function here because maybe collectstatic
    # has not been run yet
    # and it seems an empty HttpResponse or even a 204 response makes the browser
    # just keep requesting the file with every page load
    # hmmm...now it seems that chrome is not re-requesting with every page load
    # but firefox does. but if i remove the favicon, there's 1 404 then FF doesn't
    # ask for it again.


    # import os
    # dir_path = os.path.dirname(os.path.realpath(__file__))
    # with open(os.path.join(dir_path, 'favicon_invisible.ico'), 'rb') as f:
    # #with open('favicon.ico', 'rb') as f:
    #     favicon_content = f.read()
    #
    #
    # urlpatterns.append(
    #     urls.url(
    #         r'^favicon\.ico$',
    #         lambda request: HttpResponse(favicon_content, content_type="image/x-icon")
    #     )
    # )

    return urlpatterns


urlpatterns = get_urlpatterns()

otree/views/admin.py
import json
import os
import sys
from collections import OrderedDict


import channels
import otree.bots.browser
import otree.channels.utils as channel_utils
import otree.common_internal
import otree.export
import otree.models
import vanilla
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, \
    Http404
from django.shortcuts import get_object_or_404
from otree import forms
from otree.common import RealWorldCurrency
from otree.common_internal import (
    create_session_and_redirect, missing_db_tables,
    get_models_module, get_app_label_from_name, DebugTable,
)
from otree.forms import widgets
from otree_startup import check_pypi_for_updates
from otree.models import Participant, Session
from otree.models_concrete import (
    BrowserBotsLauncherSessionCode)
from otree.session import SESSION_CONFIGS_DICT, create_session, SessionConfig
from otree.views.abstract import GenericWaitPageMixin, AdminSessionPageMixin
from django.db.models import Case, Value, When
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import DeleteView

def pretty_name(name):
    """Converts 'first_name' to 'first name'"""
    if not name:
        return ''
    return name.replace('_', ' ')


class CreateSessionForm(forms.Form):
    session_configs = SESSION_CONFIGS_DICT.values()
    session_config_choices = (
        # use '' instead of None. '' seems to immediately invalidate the choice,
        # rather than None which seems to be coerced to 'None'.
        [('', '-----')] +
        [(s['name'], s['display_name']) for s in session_configs])

    session_config = forms.ChoiceField(
        choices=session_config_choices, required=True)

    num_participants = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        for_mturk = kwargs.pop('for_mturk')
        super().__init__(*args, **kwargs)
        if for_mturk:
            self.fields['num_participants'].label = "Number of MTurk workers"
            self.fields['num_participants'].help_text = (
                'Since workers can return the HIT or drop out, '
                'some "spare" participants will be created: '
                'the oTree session will have '
                '{} times more participants than the MTurk HIT. '
                'The number you enter in this field is number of '
                'workers required for your HIT.'.format(
                    settings.MTURK_NUM_PARTICIPANTS_MULTIPLE
                )
            )
        else:
            self.fields['num_participants'].label = "Number of participants"

    def clean_num_participants(self):
        session_config_name = self.cleaned_data.get('session_config')

        # I think when this is checked, it's possible that basic validation
        # for session_config_name was not done yet.
        # when I tested it was None
        # but maybe it could also be the empty string because that's what's
        # explicitly put above.
        if session_config_name:
            lcm = SESSION_CONFIGS_DICT[session_config_name].get_lcm()
            num_participants = self.cleaned_data['num_participants']
            if num_participants % lcm:
                raise forms.ValidationError(
                    'Please enter a valid number of participants.'
                )
            return num_participants


class CreateSession(vanilla.FormView):
    form_class = CreateSessionForm
    template_name = 'otree/admin/CreateSession.html'

    url_pattern = r"^create_session/$"

    def dispatch(self, request, *args, **kwargs):
        # splinter makes request.GET.get('mturk') == ['1\\']
        # no idea why
        # so just see if it's non-empty
        self.for_mturk = bool(self.request.GET.get('mturk'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs['configs'] = SESSION_CONFIGS_DICT.values()
        return super().get_context_data(**kwargs)

    def get_form(self, data=None, files=None, **kwargs):
        kwargs['for_mturk'] = self.for_mturk
        return super().get_form(data, files, **kwargs)

    def form_valid(self, form):

        session_config_name = form.cleaned_data['session_config']
        session_kwargs = {
            'session_config_name': session_config_name,
            'for_mturk': self.for_mturk
        }
        if self.for_mturk:
            session_kwargs['num_participants'] = (
                form.cleaned_data['num_participants'] *
                settings.MTURK_NUM_PARTICIPANTS_MULTIPLE
            )

        else:
            session_kwargs['num_participants'] = (
                form.cleaned_data['num_participants'])

        # TODO:
        # Refactor when we upgrade to push
        if hasattr(self, "room"):
            session_kwargs['room_name'] = self.room.name

        post_data = self.request.POST
        config = SESSION_CONFIGS_DICT[session_config_name]

        edited_session_config_fields = {}

        for field in config.editable_fields():
            old_value = config[field]
            html_field_name = config.html_field_name(field)

            # int/float/decimal are set to required in HTML
            # bool:
            # - if unchecked, its key will be missing.
            # - if checked, its value will be 'on'.
            # str:
            # - if blank, its value will be ''
            new_value_str = post_data.get(html_field_name)
            # don't use isinstance because that will catch bool also
            if type(old_value) is int:
                # in case someone enters 1.0 instead of 1
                new_value = int(float(new_value_str))
            else:
                new_value = type(old_value)(new_value_str)
            if old_value != new_value:
                edited_session_config_fields[field] = new_value

        # need to convert to float or string in order to serialize
        # through channels
        for k in ['participation_fee', 'real_world_currency_per_point']:
            if k in edited_session_config_fields:
                edited_session_config_fields[k] = float(
                    edited_session_config_fields[k])
        session_kwargs['edited_session_config_fields'] = edited_session_config_fields

        session_kwargs['user'] = self.request.user.id
        session_kwargs['username'] = self.request.user.username

        use_browser_bots = edited_session_config_fields.get('use_browser_bots')
        if use_browser_bots is None:
            use_browser_bots = config.get('use_browser_bots', False)

        return create_session_and_redirect(
            session_kwargs, use_browser_bots=use_browser_bots)


class WaitUntilSessionCreated(GenericWaitPageMixin, vanilla.GenericView):

    url_pattern = r"^WaitUntilSessionCreated/(?P<pre_create_id>.+)/$"

    title_text = 'Creating session'
    body_text = ''

    def _is_ready(self):
        try:
            self.session = Session.objects.get(
                _pre_create_id=self._pre_create_id,
                ready_for_browser=True
            )
            return True
        except Session.DoesNotExist:
            return False

    def _response_when_ready(self):
        session = self.session
        if session.is_for_mturk():
            session_home_url = reverse(
                'MTurkCreateHIT', args=(session.code,)
            )
        # 2017-09-30: deleted a line about split screen here, because
        # the only way to get split screen is to first open the session links
        # page, then switch to split-screen mode
        else:
            session_home_url = reverse(
                'SessionStartLinks', args=(session.code,))

        return HttpResponseRedirect(session_home_url)

    def dispatch(self, request, *args, **kwargs):
        self._pre_create_id = kwargs['pre_create_id']
        if self._is_ready():
            return self._response_when_ready()
        return self._get_wait_page()

    def socket_url(self):
        return channel_utils.wait_for_session_path(self._pre_create_id)


class SessionSplitScreen(AdminSessionPageMixin, vanilla.TemplateView):
    '''Launch the session in fullscreen mode
    only used in demo mode
    '''

    def get_context_data(self, **kwargs):
        '''Get the URLs for the IFrames'''
        context = super(SessionSplitScreen, self).get_context_data(**kwargs)
        participant_urls = [
            self.request.build_absolute_uri(participant._start_url())
            for participant in self.session.get_participants()
        ]
        context.update({
            'session': self.session,
            'participant_urls': participant_urls
        })
        return context


class SessionStartLinks(AdminSessionPageMixin, vanilla.TemplateView):

    def get_context_data(self, **kwargs):
        session = self.session
        room = session.get_room()

        context = super().get_context_data(**kwargs)

        sqlite = settings.DATABASES['default']['ENGINE'].endswith('sqlite3')
        context.update({
            'use_browser_bots': session.use_browser_bots(),
            'sqlite': sqlite,
            'runserver': 'runserver' in sys.argv or 'devserver' in sys.argv
        })

        session_start_urls = [
            self.request.build_absolute_uri(participant._start_url())
            for participant in session.get_participants()
        ]

        # TODO: Bot URLs, and a button to start the bots

        if room:
            context.update(
                {
                    'participant_urls':
                        room.get_participant_urls(self.request),
                    'room_wide_url': room.get_room_wide_url(self.request),

otree/templates/otree/includes/CreateSessionForm.html
{% load otree staticfiles %}

<form action="" method="post" role="form" class="form" id="form">
    {% csrf_token %}

    {% formfield form.session_config %}

    <div class="form-group{% if form.num_participants.errors %} has-error{% endif %} required">
        <label class="col-form-label" for="id_num_participants">
            {{ form.num_participants.label }}
        </label>
        <div class="controls  field-num_participants">
            {{ form.num_participants }}
            {% if form.num_participants.errors %}
                {% include "otree/forms/errors.html" with errors=form.num_participants.errors %}
            {% endif %}
            {% for config in configs %}
                <div id="lcm-{{ config.name }}" class="lcm"
                     style="display:none">
                    <p>Must be a multiple of {{ config.get_lcm }}</p></div>
            {% endfor %}
            <p class="help-block">{{ form.num_participants.help_text }}</p>
        </div>
    </div>

    <input class="btn btn-primary next-button"
           value="Create"
           type="submit">

    <br><br>
        {% for config in configs %}

            <div class="edit-config"
                 id="edit-config-{{ config.name }}" style="display: none">
                <h4>
                    <a data-toggle="collapse"
                       href="#edit-config-table-{{ config.name }}"
                       class="btn-block">
                        Configure session
                        <img src='{% static "glyphicons/cogwheel.png" %}'>
                    </a>
                </h4>
                <div class="collapse"
                     id="edit-config-table-{{ config.name }}">
                    {% if config.custom_editable_fields %}
                        <h5>Custom</h5>
                        <table class="table">
                            {% for field in config.custom_editable_fields_html %}
                                {{ field|safe }}
                            {% endfor %}
                        </table>
                    {% else %}
                        <p><i>
                            You can make more properties configurable
                            by adding them to your session config in
                            settings.py.
                        </i></p>
                    {% endif %}

                    {# we only need to clarify that these are built-in if there are also custom ones #}
                    {% if config.custom_editable_fields %}
                        <h5>General</h5>{% endif %}
                    <table class="table">
                        {% for field in config.builtin_editable_fields_html %}
                            {{ field|safe }}
                        {% endfor %}
                    </table>
                </div>
            </div>


            {% include "otree/includes/SessionInfo.html" with config=config config_display="none" %}

        {% endfor %}
</form>

<script>
    function showSessionConfigInfo(sessionconfigname) {
        $('.summary').hide();
        $('.edit-config').hide();
        $('#session-config-' + sessionconfigname).show();
        $('#edit-config-' + sessionconfigname).show();
        $('.lcm').hide();
        $('#lcm-' + sessionconfigname).show();
    }

    $(document).ready(function () {
        $('.summary').hide();
        $('.edit-config').hide();
        $('.lcm').hide();
        var current_session_config = $('#id_session_config').val();
        if (current_session_config) {
            showSessionConfigInfo(current_session_config);
        }

        $('#id_session_config').change(function () {
            showSessionConfigInfo($(this).val());
        })
    });
</script>

otree/templates/otree/includes/OtreeDotOrgFeedbackWidget.html
<script>
// Include the UserVoice JavaScript SDK (only needed once on a page)
UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/FeVK48347qPrRUQSnZ8uw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();

//
// UserVoice Javascript SDK developer documentation:
// https://www.uservoice.com/o/javascript-sdk
//

// Set colors
UserVoice.push(['set', {
  accent_color: '#448dd6',
  trigger_color: 'white',
  trigger_background_color: 'rgba(46, 49, 51, 0.6)'
}]);

// Identify the user and pass traits
// To enable, replace sample data with actual user traits and uncomment the line
UserVoice.push(['identify', {
  //email:      'john.doe@example.com', // User’s email address
  //name:       'John Doe', // User’s real name
  //created_at: 1364406966, // Unix timestamp for the date the user signed up
  //id:         123, // Optional: Unique id of the user (if set, this should not change)
  //type:       'Owner', // Optional: segment your users by type
  //account: {
  //  id:           123, // Optional: associate multiple users with a single account
  //  name:         'Acme, Co.', // Account name
  //  created_at:   1364406966, // Unix timestamp for the date the account was created
  //  monthly_rate: 9.99, // Decimal; monthly rate of the account
  //  ltv:          1495.00, // Decimal; lifetime value of the account
  //  plan:         'Enhanced' // Plan name for the account
  //}
}]);

// Add default trigger to the bottom-right corner of the window:
UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);

// Or, use your own custom trigger:
//UserVoice.push(['addTrigger', '#id', { mode: 'contact' }]);

// Autoprompt for Satisfaction and SmartVote (only displayed under certain conditions)
UserVoice.push(['autoprompt', {}]);
</script>

otree/templates/otree/includes/RoomParticipantLinks.html
<h3>Persistent URLs</h3>

<p>
    These URLs will stay constant for new sessions,
    even if the database is recreated.
</p>


{% if room.has_participant_labels %}
<h4>Participant-specific URLs</h4>

    <p>
        These URLs contain the labels,
        so participants don't have to enter their label manually.
    </p>

    {% if collapse_links %}
    <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#participant_links">
            Show/Hide
    </button>

    {% endif %}


    <div id="participant_links" {% if collapse_links %}class="collapse"{% endif %}>
    {% comment %}
        this is a table to be consistent with other start links listings,
        which may include participant label column
    {% endcomment %}
    <table class="table">
    {% for participant_url in participant_urls %}
        <tr>
            {# eventually add participant labels #}
            <td><a href="{{ participant_url }}" class="participant-link" target="_blank">{{ participant_url }}</a></td>
        </tr>
    {% endfor %}
    </table>
    </div>

{% endif %}


{% if room.use_secure_urls %}
    {# then dont use room-wide URL #}
{% else %}
    <br>
    <h4>Room-wide URL</h4>
    <p>
        Here is the room-wide URL anyone can use.
        {% if room.has_participant_labels %}
            Users will be prompted to enter their participant label,
            which will be validated against your participant_label_file.
        {% else %}
            Don't use this link when testing in multiple tabs on the same browser,
            because all tabs will be assigned to the same participant,
            using a cookie.
        {% endif %}
    </p>

    <p><a href="{{ room_wide_url }}" target="_blank">{{ room_wide_url }}</a></p>
{% endif %}

<br>

otree/templates/otree/includes/SessionInfo.html
<div id="session-config-{{ config.name }}" class="summary" style="display:{{ config_display|default_if_none:"block" }}">

{% if config.doc %}
    <h4>Session description</h4>
    <p>
    {{ config.doc|safe }}
    </p>
{% endif %}

<h4>App sequence</h4>
<table class="table table-hover">

{% for app in config.app_sequence_display %}
    <tr>
        <th>{{ app.name }}</th>
        <td>
            <p>
                {{ app.doc|safe }}
            </p>
        </td>
    </tr>
{% endfor %}
</table>

</div>

otree/templates/otree/includes/TimeLimit.html
{% load static %}
{% load i18n %}

<div class="otree-timer alert alert-warning">
    <p>{{ timer_text }}
        <span style="font-weight: bold">
            <span class="otree-timer__time-left"></span>
        </span>
    </p>
</div>

otree/templates/otree/includes/TimeLimit.js.html
{% load staticfiles otree %}
<script src="{% static 'otree/js/jquery.countdown.min.js' %}"></script>

<script>
    $(function () {
        var currentDate = new Date();
        var remainingTimeoutSeconds = {{ view.remaining_timeout_seconds|json }};
        var milliseconds = Math.floor(remainingTimeoutSeconds * 1000);
        $('.otree-timer__time-left').countdown(currentDate.valueOf() + milliseconds)
            .on('update.countdown', function (event) {
                // %-N is "Total count of minutes till the end, non-padded"
                // %S is seconds left
                var format = '%-N:%S';
                $(this).html(event.strftime(format));
            })
            .on('finish.countdown', function (event) {
                $('<input>').attr({
                    type: 'hidden',
                    name: 'timeout_happened',
                    value: '1'
                }).appendTo('form');
                $('#form').submit();
            });
    });
</script>

otree/templates/otree/includes/debug_info.html
{% load staticfiles otree %}
{# spaces to make debug info less distracting #}
<br/>
<br/>
<br/>


<div class="card debug-info"> {# .debug-info so it's visible in inspector #}
    <h5 class="card-header">Debug info</h5>

    {% include 'otree/includes/hidden_form_errors.html' %}

{% for table in view.debug_tables|default:None %}
    <div class="card-body">
        <h6 class="card-title">{{ table.title }}</h6>
        <div class="scrollable">
            <table class="table table-hover table-debug">
                {% for k, v in table.rows %}
                    <tr>
                        <td class="debug-var-name">{{ k }}</td>
                        <td class="debug-var-value">
                            <code>{{ v }}</code>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endfor %}

</div>

otree/templates/otree/includes/hidden_form_errors.html
{% if view.first_field_with_errors|default:False %}
    <div id="hidden-form-errors-warning" class="card-body" style="display: none;">
        <div class="alert alert-warning">
            <p>
                The form field <code>{{ view.first_field_with_errors }}</code> has errors,
                but its error message is not being displayed, possibly because
                you did not include the field in the page.
                There are 2 ways to fix this:
            <ol>
                <li>
                    Include the field with the <code>formfield</code> tag, e.g.
                    <code>{% templatetag openblock %}
                        formfield player.{{ view.first_field_with_errors }}
                        {% templatetag closeblock %}</code>
                </li>
                <li>
                    If you are not using <code>formfield</code> but are instead
                    writing the raw HTML for the form input,
                    remember to include
                    <code>{% templatetag openvariable %}
                        form.{{ view.first_field_with_errors }}.errors
                        {% templatetag closevariable %}</code>
                    somewhere in your page's HTML.
                </li>
            </ol>

            {% if view.other_fields_with_errors %}
                <p>The following other field(s) have the same issue:</p>
                <ul>
                    {% for field_with_error in view.other_fields_with_errors %}
                        <li>
                            <code>{{ field_with_error }}</code>
                        </li>
                    {% endfor %}
                </ul>
                <p>
                    While debugging, you can display all errors in the form with
                    <code>{% templatetag openvariable %}
                        form.errors
                        {% templatetag closevariable %}</code>.
                </p>
            {% endif %}
        </div>
    </div>
    {% comment %}
        formfield: <div class="form-control-errors">error</div>
        form.errors or form.foo.errors: <ul class="errorlist"></ul>
    {% endcomment %}
    <script>
        window.addEventListener('load', function () {
            var django_form_errors = document.querySelector('ul.errorlist');
            var floppy_form_errors = document.querySelector('div.form-control-errors');
            if (django_form_errors === null && floppy_form_errors === null) {
                document.querySelector("#hidden-form-errors-warning").style.display = "block";
            }
        });
    </script>


{% endif %}

otree/templates/otree/includes/messages.html
{% for message in messages %}
    <div class="alert alert-{{ message.tags.split|last }}">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
    </div>
{% endfor %}